### ISSUE TITLE
Can it be enabled again?

### ISSUE THREAD

**Issue by xinkeng0** [elect86/java-unofficial-opengl-SDK#4]
I know it has a Kotlin version.
However, for me, the cost of introducing Kotlin in a Java project is too high.
Thanks.

**Comment by elect86** [comment]
Hi Orange,

Honestly there is very little reason for me to work on this, since I migrated it to Kotlin and it's almost 100% java compatible

The cool thing is that you do not need to introduce kotlin in your project at all, you have just to add it as dependency and call it from Java as you would do with any other lib

I can help you with that if you are available and tell me which building tool you use

Otherwise, another option is for you to jump in and directly take lead in this project

Giuseppe

**Comment by xinkeng0** [comment]
Hi Giuseppe.
I am using Intellij IDEA.
Just a little worried because I am not familiar with him.
I will to add it as dependency.
Thanks!

**Comment by elect86** [comment]
Are you using Gradle/Maven/other?

**Comment by xinkeng0** [comment]
Maven
